[workspace]
resolver = "3"
members = [
    "uju",
    "uju-demo",
    "uju-ecs",
    "uju-ecs/macros",
    "uju-io",
    "uju-mesh",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bytes = "1"
compio = { version = "0.19", features = ["macros", "net", "signal", "time"] }
crossfire = "3.1"
futures-util = "0.3"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
smallvec = "1.15"
thiserror = "2"
tracing = "0.1"
