[package]
name = "uju-mesh"
version.workspace = true
edition.workspace = true

[dependencies]
uju-io = { path = "../uju-io" }

compio.workspace = true
crossfire.workspace = true
futures-util.workspace = true
nix = { version = "0.31", features = ["sched"] }
thiserror.workspace = true
tracing.workspace = true
