[package]
name = "uju"
version.workspace = true
edition.workspace = true

[dependencies]
uju-macros-ecs = { path = "macros/ecs" }

bytes.workspace = true
compio.workspace = true
crossfire.workspace = true
futures-util.workspace = true
libc.workspace = true
linkme = "0.3"
nix = { version = "0.31", features = ["sched"] }
socket2 = "0.6"
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true
